apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pokeapi
  name: pokeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
      - image: razannadhif/minpropokeap:latest
        name: pokeapi
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "700m"
            memory: "750Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pokeapi
  name: pokeapi
spec:
  ports:
  - name: "http-pokeapi"
    port: 80
    targetPort: 8080
  selector:
    app: pokeapi
  type: LoadBalancer
