apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: minpropokeapi
  type: LoadBalancer