apiVersion: apps/v1
kind: Deployment
metadata:
  name: minpropokeapi-flask
spec:
  selector:
    matchLabels:
      app: minpropokeapi
  template:
    metadata:
      labels:
        app: minpropokeapi
    spec:
      containers:
      - name: minpropokeapi
        image: razannadhif/minpropokeapi:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080                          
        # livenessProbe:                            
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      # imagePullSecrets:
      #   - name: melissa-hol-group
---
apiVersion: v1
kind: Service
metadata:
  name: minpropokeapi-svc
spec:
  selector:
    app: minpropokeapi
  ports:
  - port: 80
    targetPort: 8080