---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minpropokeapi
  labels:
    app: minpropokeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minpropokeapi
  # pod spec begins here
  template:
    metadata:
      labels:
        app: minpropokeapi
    spec:
      containers:
        - name: minpropokeapi
          image: razannadhif/minpropokeapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: APP_ENV
            value: "development"
          - name: APP_DEBUG
            value: True
          - name: APP_PORT
            value: 8080

          command: ["python", "file.py"]