apiVersion: v1
kind: Namespace
metadata:
  name: mini-project-pokeapi-develop
---
apiVersion: v1
kind: Service
metadata:
  name: mini-project-pokeapi-svc
  namespace: mini-project-pokeapi-develop
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: mini-project-pokeapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-project-pokeapi-flask
  namespace: mini-project-pokeapi-develop
spec:
  selector:
    matchLabels:
      app: mini-project-pokeapi
  template:
    metadata:
      labels:
        app: mini-project-pokeapi
    spec:
      containers:
      - image: razannadhif/mini-project-pokeapi:1.0.0
        imagePullPolicy: Always
        name: mini-project-pokeapi
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 1m
            memory: 1Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-project-pokeapi-ingress
  namespace: mini-project-pokeapi-develop
spec:
  ingressClassName: nginx
  rules:
  - host: pokecanov.shamirhusein.my.id
    http:
      paths:
      - backend:
          service:
            name: mini-project-pokeapi-svc
            port:
              number: 80
        path: /
        pathType: Prefix
